esphome:
  name: esp32-zona-puerta
  friendly_name: esp32-zona-puerta

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: 'Livebox6s-4ADB_EXT'
  password: 'PjEM5okD45N4'

api:

ota:
  - platform: esphome

# 1. SENSOR DE PUERTA MAGNETICO
binary_sensor:
  - platform: gpio
    pin:
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    name: 'Sensor Puerta'
    device_class: door
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
